version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:14.2
    environment:
      POSTGRES_DB: "my_first_app"
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: controller/Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/my_first_app
      - SPRING_DATASOURCE_USERNAME=docker
      - SPRING_DATASOURCE_PASSWORD=docker
    ports:
      - "8080:8080"
    links:
      - postgres
    depends_on:
      - postgres

volumes:
  postgres-data:
#  sonarqube_data:
#  sonarqube_extensions:
#  sonarqube_logs:
#  sonarqube:
#    image: sonarqube:community
#    depends_on:
#      - postgres
#    environment:
#      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/my_first_app
#      SONAR_JDBC_USERNAME: docker
#      SONAR_JDBC_PASSWORD: docker
#    volumes:
#      - sonarqube_data:/opt/sonarqube/data
#      - sonarqube_extensions:/opt/sonarqube/extensions
#      - sonarqube_logs:/opt/sonarqube/logs
#    ports:

#      - "9000:9000"
