version: "3.0"
services:
  mongo:
    image: "mongo"
    container_name: "my-mongo-container"
    environment:
      - MONGO_INITDB_DATABASE=my_mongodb
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=docker
    volumes:
      - ~/apps/mongo:/data/db
    ports:
      - "27017:27017"

  postgres:
    container_name: postgres-db
    image: postgres:14.2
    environment:
      POSTGRES_DB: "my_first_app"
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

  postgres-test:
    container_name: postgres-db-test
    image: postgres:14.2
    environment:
      POSTGRES_DB: "my_first_app_test"
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - posrgres-data-test:/var/lib/postgresql/data

  app:
    container_name: my-app
    build:
      context: .
      dockerfile: controller/Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/my_first_app
      - SPRING_DATASOURCE_URL_TEST=jdbc:postgresql://postgres-test:5433/my_first_app_test
      - SPRING_DATA_MONGODB_URI=mongodb://docker:docker@mongo:27017/
      - SPRING_DATASOURCE_USERNAME=docker
      - SPRING_DATASOURCE_PASSWORD=docker
    ports:
      - "8080:8080"
    links:
      - postgres-test
      - postgres
      - mongo
    depends_on:
      - postgres-test
      - postgres
      - mongo

volumes:
  postgres-data:
  posrgres-data-test:
