-- liquibase formatted sql

-- changeset vyacheslav:1646923667211-3
CREATE TABLE if not exists authority (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT authority_pkey PRIMARY KEY (id));