-- liquibase formatted sql

-- changeset vyacheslav:1646923667211-7
CREATE TABLE if not exists role (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, CONSTRAINT role_pkey PRIMARY KEY (id));
