-- liquibase formatted sql

-- changeset vyacheslav:1646923667211-4
CREATE TABLE if not exists grades (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, theme_name VARCHAR(50) NOT NULL, grade INTEGER NOT NULL, student_id INTEGER, CONSTRAINT grades_pkey PRIMARY KEY (id));
