-- liquibase formatted sql

-- changeset vyacheslav:1646923667211-1
CREATE TABLE if not exists users (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_name VARCHAR(50) NOT NULL, password VARCHAR(255), name VARCHAR(50), age INTEGER, user_type VARCHAR(50), CONSTRAINT users_pkey PRIMARY KEY (id));
