CREATE TABLE users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name VARCHAR(50)                             NOT NULL,
    password  VARCHAR(255),
    name      VARCHAR(50),
    age       INTEGER,
    user_type VARCHAR(50),
    CONSTRAINT users_pkey PRIMARY KEY (id)
);
